### PR TITLE
feat: custom http client

### PR DESCRIPTION
**Pull request by Vinzent03**
The journey goes on... See https://github.com/supabase-community/postgrest-dart/pull/66 for a detailed reason.

In addition, I added status code to the response and made the properties of the data classes final.

### CODE REVIEW

**Comment by Vinzent03** [comment]
@dshukertjr May you review this?

**Review by dshukertjr — APPROVED** [review]
@Vinzent03 Sorry it took so long to take look and thank you as usual for the amazing work!

**Comment by Vinzent03** [comment]
@dshukertjr Thanks for merging! Are you going to release a new version, or should I add another pr?

**Comment by dshukertjr** [comment]
@Vinzent03 Sorry for taking time one this one. Will release this one pretty soon!

**Pull request merged**
